# Generated by Django 4.1.6 on 2023-02-11 21:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="reciever",
            new_name="receiver",
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("sender", "receiver")},
        ),
    ]
