# Generated by Django 4.1.6 on 2023-02-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="message",
            unique_together=set(),
        ),
    ]
